FROM codercom/code-server:latest

USER root

RUN apt update \
    && apt upgrade \
    && apt install -y curl gcc unzip

USER coder

SHELL ["/bin/bash", "-c"]

ENV FNM_DIR="/home/coder/.local/share/fnm"
ENV PATH="${FNM_DIR}:${PATH}"

RUN curl -fsSL https://fnm.vercel.app/install | bash -s -- --install-dir "$FNM_DIR" --skip-shell

RUN eval "$(fnm env --shell bash)" \
    && fnm install --latest \
    && fnm alias "$(fnm current)" default \
    && npm install -g npm@latest pnpm @opencode/cli

ENV PATH="${FNM_DIR}/aliases/default/bin:${PATH}"

WORKDIR /home/coder/workspace
